### ISSUE TITLE
Фэн-шуй на const-овость

### ISSUE THREAD

**Issue by avasyukov** [tyurinatanya/HWLinal#2]
Этот тикет - самые последние штрихи на линал.

Логически по смыслу операций у примерно всех операторов (кроме чтения из потока) следует ожидать:
- const-овость в отношении текущего объекта (this-а)
- const-овость в отношении второго операнда (параметр, переданный по ссылке)

Сейчас const-овость лоскутная - где-то есть, где-то забыта. Нужно её расставить до конца.

**Comment by tyurinatanya** [comment]
Здравствуйте!
Контейнер:

https://github.com/tyurinatanya/AvlTreeClass

Проект (броуновское движение):

https://github.com/tyurinatanya/Brownian-motion

Линал (обновлены const):

https://github.com/tyurinatanya/HWLinal

К сожалению, не успела проверить сборку cmake-ом  для контейнера и
"проекта" (всё было просто в одном проекте в IDE). Проект в данном случае -
что-то вроде первого приближения, т.к. завал по всем предметам и времени
было не особо много.

пт, 8 мая 2020 г. в 14:36, Alexey Vasyukov <notifications@github.com>:

**Comment by avasyukov** [comment]
Линал стал полностью ок, тикет закрываю
